[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://oncovision-backend-mp8n.onrender.com/api/v1"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
